"""Phase 1 output: component catalog viewer, stand-in STLs, dimension table.
Usage: python make_components.py OUT_DIR
Writes OUT_DIR/ms2000-components.html, OUT_DIR/components/<name>.stl,
       OUT_DIR/ms2000-dims.json, OUT_DIR/components-check.png, and DIMENSIONS.md next to this file."""
import os, sys, json
import numpy as np, trimesh
from components import COMPONENTS, HARDWARE, arrays

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'out')
os.makedirs(os.path.join(OUT, 'components'), exist_ok=True)

GAP = 14.0
ORDER = ['huskylens', 'xiami', 'microbit', 'servo', 'laser', 'speaker', 'aa_pack', 'aaa_pack',
         'arm_switch', 'light_sensor', 'led', 'stuffy']
BASIS = {'photo': 'from photo', 'ds': 'datasheet', 'step': 'maker 3D model', 'est': 'estimate', 'tbd': 'unknown until it arrives', 'cal': 'measured'}

items, allv, x = [], [], 0.0
row_y = 0.0
for i, name in enumerate(ORDER):
    c = COMPONENTS[name]
    v, f, ref = arrays(name)
    t = trimesh.Trimesh(v, f, process=False)
    t.export(os.path.join(OUT, 'components', f'{name}.stl'))
    lo, hi = v.min(0), v.max(0)
    if i == 6:                                   # second row
        x, row_y = 0.0, -110.0
    shift = np.array([x - lo[0], row_y - lo[1], -lo[2]])
    vp = v + shift
    x += (hi[0] - lo[0]) + GAP
    b = [vp.min(0).tolist(), vp.max(0).tolist()]
    counts = {}
    for k, dd in c['dims'].items():
        counts[dd['basis']] = counts.get(dd['basis'], 0) + 1
    open_items = [f"{k}: {dd['note']}" for k, dd in c['dims'].items() if dd['basis'] in ('tbd',)]
    note = c['role'] + ' Numbers: ' + ', '.join(f'{n} {BASIS[k]}' for k, n in counts.items()) + '.'
    if open_items:
        note += ' Open: ' + '; '.join(open_items) + '.'
    items.append({'k': name, 'n': c['label'], 'g': 'bought', 'q': c['qty'], 's': c['sku'], 'note': note,
                  'c': c['color'], 'size': [round(float(q), 1) for q in (hi - lo)], 'sb': b, 'b': b, 'gr': None,
                  'v': np.round(vp, 2).flatten().tolist(), 'f': f.flatten().tolist()})
    allv.append(vp)
allv = np.vstack(allv)
nchk = sum(1 for c in COMPONENTS.values() for dd in c['dims'].values() if dd['basis'] in ('est', 'tbd', 'photo'))
nds = sum(1 for c in COMPONENTS.values() for dd in c['dims'].values() if dd['basis'] in ('ds', 'step', 'cal'))
data = {'items': items, 'bounds': [allv.min(0).tolist(), allv.max(0).tolist()],
        'summary': [['Bought parts', str(len(items))], ['Numbers confirmed', str(nds)], ['To measure', str(nchk)]]}
tpl = open(os.path.join(HERE, 'catalog.tpl.html')).read()
for a, b_ in [("'Whole turret'", "'All parts'"), ('In turret', 'In lineup'),
              ('Tap a part below to see it alone with its measurements, or in place on the turret.',
               'Stand-ins for every bought part, built from datasheet numbers. Tap one to see its size and which numbers still need calipers.')]:
    tpl = tpl.replace(a, b_)
open(os.path.join(OUT, 'ms2000-components.html'), 'w').write(tpl.replace('__DATA__', json.dumps(data, separators=(',', ':'))))

# dimension table (json for the site, markdown for the repo)
dump = {'components': {k: {kk: vv for kk, vv in c.items()} for k, c in COMPONENTS.items()}, 'hardware': HARDWARE}
json.dump(dump, open(os.path.join(OUT, 'ms2000-dims.json'), 'w'), indent=1)
md = ['# MS-2000 component dimensions', '',
      'Generated by make_components.py from components.py. Edit numbers there, not here.',
      'Basis: ds = datasheet, photo = scaled from a product photo, step = maker 3D model, est = estimate (calipers on arrival), tbd = unknown until it arrives, cal = measured.', '']
for k in ORDER:
    c = COMPONENTS[k]
    md += [f"## {c['label']} ({k}) x{c['qty']}", f"{c['sku']}. {c['role']}", '', '| key | mm | basis | note |', '|---|---|---|---|']
    md += [f"| {kk} | {'' if dd['v'] is None else dd['v']} | {dd['basis']} | {dd['note']} |" for kk, dd in c['dims'].items()]
    md.append('')
md += ['## Hardware rules', '', '| key | value | basis | note |', '|---|---|---|---|']
md += [f"| {kk} | {dd['v']} | {dd['basis']} | {dd['note']} |" for kk, dd in HARDWARE.items()]
open(os.path.join(HERE, 'DIMENSIONS.md'), 'w').write('\n'.join(md) + '\n')

# quick check render
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
fig = plt.figure(figsize=(12, 7))
ax = fig.add_subplot(111, projection='3d')
for it in items:
    vv = np.array(it['v']).reshape(-1, 3); ff = np.array(it['f']).reshape(-1, 3)
    if len(ff) > 6000:
        ff = ff[::max(1, len(ff)//6000)]
    ax.add_collection3d(Poly3DCollection(vv[ff], facecolor=it['c'], edgecolor='k', linewidth=.05))
lo, hi = allv.min(0), allv.max(0)
ax.set_xlim(lo[0], hi[0]); ax.set_ylim(lo[1], hi[1]); ax.set_zlim(lo[2], hi[2])
ax.set_box_aspect(tuple(np.maximum(hi - lo, 1))); ax.view_init(35, -60)
plt.savefig(os.path.join(OUT, 'components-check.png'), dpi=80); plt.close(fig)
for it in items:
    print(f"{it['k']:13s} x{it['q']:<2d} {it['size']}")
print('html KB', os.path.getsize(os.path.join(OUT, 'ms2000-components.html')) // 1024)
